name: Stop Discord Bot

on:
  workflow_dispatch:
    branches:
      - main

env:
  PYTHON_VERSION: '3.10'

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      # 1. 환경 설정
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. docker container 정지하기
      - name: Stop Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.APP_FOLDER_PATH }}
            if docker ps -a -q --filter "name=${{ secrets.DOCKER_CONTAINER_NAME }}" | grep -q .; then
              if docker ps -q --filter "name=${{ secrets.DOCKER_CONTAINER_NAME }}" | grep -q .; then
                echo "INFO: Bot Container is stopping..."
                docker stop ${{ secrets.DOCKER_CONTAINER_NAME }} || true
                echo "INFO: Bot Container is removing... True"
                docker rm ${{ secrets.DOCKER_CONTAINER_NAME }} || true
              else
                echo "INFO: Bot Container is removing... True"
                docker rm ${{ secrets.DOCKER_CONTAINER_NAME }} || true
              fi
            else
              echo "ERROR: Bot Container is not exists... False"
            fi