name: Start Discord Bot

on:
  workflow_dispatch:
    branches:
      - main

env:
  PYTHON_VERSION: '3.10'

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      # 1. 환경 설정
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. docker container 실행하기
      - name: Start Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if docker ps -a -q --filter "name=${{ secrets.DOCKER_CONTAINER_NAME }}" | grep -q .; then
              if docker ps -q --filter "name=${{ secrets.DOCKER_CONTAINER_NAME }}" | grep -q .; then
                echo "ERROR: Bot Container is running... False"
              else
                echo "ERROR: Bot Container is exists... False"
                echo "INFO: Bot Container is removing..."
                docker rm ${{ secrets.DOCKER_CONTAINER_NAME }} || true
              fi
            elif docker image inspect {{ secrets.DOCKER_IMAGE_NAME }}:latest &> /dev/null; then
              echo "INFO: Bot Container is starting... True"
              docker run -d --name ${{ secrets.DOCKER_CONTAINER_NAME }} -v $(pwd)/db:/db -p 80:80 ${{ secrets.DOCKER_IMAGE_NAME }}
            else
              echo "ERROR: Bot Docker Image is none... False"
            fi