name: Restart Discord Bot

on:
  workflow_dispatch:
    branches:
      - main

env:
  PYTHON_VERSION: '3.10'

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      # 1. 환경 설정
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. docker container 재실행하기
      - name: Restart Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.APP_FOLDER_PATH }}
            docker stop ${{ secrets.DOCKER_CONTAINER_NAME }} || true
            docker rm ${{ secrets.DOCKER_CONTAINER_NAME }} || true
            docker run -d --name ${{ secrets.DOCKER_CONTAINER_NAME }} -v $(pwd)/db:/db ${{ secrets.DOCKER_IMAGE_NAME }}