name: Deploy Discord Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

env:
  PYTHON_VERSION: '3.10'
  FOLDER_PATH: '/home/discord'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 환경 설정
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
        
      - name: Setup Python venv
        run: python -m venv venv
      
      - name: Install dependencies
        run: ./venv/bin/python -m pip install -r requirements.txt

      - name: Make zip file
        run: sudo zip -qq -r ./bot.zip .
        shell: bash
      
      - name: checking
        run: |
          pwd
          ls -al
        shell: bash

      # - name: Close and Delete file
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST_NAME }}
      #     username: ${{ secrets.USER_NAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: ${{ secrets.SSH_PORT }}
      #     script: |
      #       cd ${{ env.FOLDER_PATH }}
      #       screen -S dc -X quit
      #       find ${{ env.FOLDER_PATH }} -type d ! -name 'data' -exec rm -rf {} +
      #       rm ${{ env.FOLDER_PATH }}/data/Functions.py
      #       rm ${{ env.FOLDER_PATH }}/data/sokobanMap.py
      #       rm ${{ env.FOLDER_PATH }}/data/Timeout.py
      
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.HOST_NAME}}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          local-dir: /home/runner/work/discordBot/discordBot
          server-dir: /home/discord
          security: loose
          protocol: ftps

      # - name: Deploy
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.HOST_NAME }}
      #     username: ${{ secrets.USER_NAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     source: "./bot.zip"
      #     target: "/home/${{ secrets.HOST_NAME }}/discord"
      
      # - name: Unzip file
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST_NAME }}
      #     username: ${{ secrets.USER_NAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: ${{ secrets.SSH_PORT }}
      #     script: |
      #       unzip ${{ env.FOLDER_PATH }}/bot.zip -d ${{ env.FOLDER_PATH }}