name: Deploy Discord Bot

on:
  push:
     branches:
       - main
     paths-ignore:
       - '.github/workflows/**'
       - 'src/**'
       - '**/*.md'
  workflow_dispatch:
    branches:
      - main

env:
  PYTHON_VERSION: '3.10'
  ZIP_NAME: 'discord-bot.zip'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 환경 설정
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. 소스 코드 압축
      - name: Make zip file
        run: zip -qq -r ./${{ env.ZIP_NAME }} . -x ".git/*" ".github/*" "src/*" "mainTest.py"
        shell: bash

      # 3. scp로 압축파일 보내기
      - name: Copy discord bot code
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "${{ env.ZIP_NAME }}"
          target: ${{ secrets.APP_FOLDER_PATH }}/

      # 4. 압축파일을 해제하고 docker container로 실행하기
      - name: Connect to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.APP_FOLDER_PATH }}
            unzip -o ${{ env.ZIP_NAME }}
            rm ${{ env.ZIP_NAME }}
            docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} .
            docker stop ${{ secrets.DOCKER_CONTAINER_NAME }} || true
            docker rm ${{ secrets.DOCKER_CONTAINER_NAME }} || true
            docker run -d --name ${{ secrets.DOCKER_CONTAINER_NAME }} -v $(pwd)/db:/db -p 80:80 ${{ secrets.DOCKER_IMAGE_NAME }}
            docker rmi $(docker images -f "dangling=true" -q) || true