name: Deploy Discord Bot

on:
  push:
     branches:
       - main
  workflow_dispatch:
    branches:
      - main

env:
  PYTHON_VERSION: '3.10'
  FOLDER_PATH: '/home/app'
  ZIP_NAME: 'discord-bot.zip'
  DOCKER_IMAGE_NAME: 'python-discord-bot'
  CONTAINER_NAME: 'discord-bot'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 환경 설정
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Make zip file
        run: zip -qq -r ./${{ env.ZIP_NAME }} . -x ".git/*" ".github/*" "img/*" "mainTest.py"
        shell: bash

      - name: Modify permissions of Zip file
        run: chmod o+rwx ${{ env.ZIP_NAME }}

      - name: Copy discord bot code
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "${{ env.ZIP_NAME }}"
          target: ${{ env.FOLDER_PATH }}/

      - name: Connect to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.FOLDER_PATH }}
            unzip -o ${{ env.ZIP_NAME }}
            rm ${{ env.ZIP_NAME }}
            docker build -t ${{ env.DOCKER_IMAGE_NAME }} .
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true
            docker run -d --name ${{ env.CONTAINER_NAME }} -v $(pwd)/db:/db -p 80:80 ${{ env.DOCKER_IMAGE_NAME }}
            docker rmi $(docker images -f "dangling=true" -q) || true