name: Track Changes

on:
  push:
    branches:
      - develop

jobs:
  track_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Check changed files
      run: |
        # 현재 브랜치 확인
        git branch
        
        # 파일 상황 확인
        ls -al
        
        # Get the commit SHA of the latest commit
        latest_commit=$(git rev-parse HEAD)

        # Get the commit SHA of the commit before the latest commit
        previous_commit=$(git rev-list -n 1 $latest_commit^ --)

        # List the changed files between the latest commit and the previous commit
        changed_files=$(git diff --name-only $previous_commit $latest_commit)

        # Print the changed files
        echo "Changed files:"
        echo "$changed_files"